version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: real_estate_db
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: realestate
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
